baseURL = "https://yujinz.me/"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "Yujin Zhang"
theme = "digital-garden"
disqusShortname = "digital-garden"
canonifyurls = true


[params]
  name = "Yujin Zhang"
  description = "Hi :) I'm a backend software engineer in San Francisco Bay Area. I enjoy going to parks, commuting by bike and Caltrain, organizing my home, reading fictions, watching animations, and playing Nintendo Switch."
  initials = "Pronounced yoo-JEEN jaang"
  googleAnalytics = ""

  [[params.social]]
    name = "Github"
    link = "https://github.com/yujinz/"
    icon = "fab fa-github"

  [[params.social]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/yujinz/"
    icon = "fab fa-linkedin-in"


[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blogs"
    url = "/garden/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4


[taxonomies]
  blog_tags = 'blog_tags'
  project_tags = 'project_tags'


[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'monokailight'